name: Mostrar hola
on:
  push:
    branch: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mostrar hola en la pantalla
      run: |
        echo "Hola, me llamo Eomat, hoy es"
        date
        ls
        echo "Version de Java: "
        java -version || echo "Java no instalado"